//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanici()
        {
            this.KullaniciRol = new HashSet<KullaniciRol>();
            this.Makale = new HashSet<Makale>();
            this.Kullanici1 = new HashSet<Kullanici>();
            this.Kullanici2 = new HashSet<Kullanici>();
        }
    
        public int id { get; set; }
        public string adi { get; set; }
        public string soyadi { get; set; }
        public string kullaniciAdi { get; set; }
        public string parola { get; set; }
        public string aciklama { get; set; }
        public string mailAdres { get; set; }
        public Nullable<bool> cinsiyet { get; set; }
        public Nullable<System.DateTime> dogumTarihi { get; set; }
        public System.DateTime kayitTarihi { get; set; }
        public Nullable<int> resimID { get; set; }
        public Nullable<bool> yazar { get; set; }
        public Nullable<bool> onaylandi { get; set; }
        public Nullable<bool> aktif { get; set; }
    
        public virtual Resim Resim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KullaniciRol> KullaniciRol { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Makale> Makale { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici> Kullanici1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Kullanici> Kullanici2 { get; set; }
    }
}
