//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KullaniciRol
    {
        public int id { get; set; }
        public int rolID { get; set; }
        public int kullaniciID { get; set; }
    
        public virtual Kullanici Kullanici { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
