//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Makale
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Makale()
        {
            this.Resim1 = new HashSet<Resim>();
            this.Yorum = new HashSet<Yorum>();
            this.Etiket1 = new HashSet<Etiket>();
        }
    
        public int id { get; set; }
        public string baslik { get; set; }
        public string icerik { get; set; }
        public System.DateTime eklenmeTarihi { get; set; }
        public int goruntulenmeSayisi { get; set; }
        public int begeni { get; set; }
        public int kategoriID { get; set; }
        public int yazarID { get; set; }
        public Nullable<int> resimID { get; set; }
        public Nullable<int> etiketID { get; set; }
    
        public virtual Etiket Etiket { get; set; }
        public virtual Kategori Kategori { get; set; }
        public virtual Kullanici Kullanici { get; set; }
        public virtual Resim Resim { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Resim> Resim1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Yorum> Yorum { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Etiket> Etiket1 { get; set; }
    }
}
