//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WBlog.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Yorum
    {
        public int id { get; set; }
        public string yorum1 { get; set; }
        public System.DateTime eklenmeTarihi { get; set; }
        public string adSoyad { get; set; }
        public int begeni { get; set; }
        public int makaleID { get; set; }
    
        public virtual Makale Makale { get; set; }
    }
}
